config/routes.rb
EasyOta::Application.routes.draw do
  resources :devices

  devise_for :users

  resources :versions
  
  resources :apps do
    resources :versions do
      get 'wrapper', :on => :member
      get 'plist', :on => :member
    end
  end

  root :to => "apps#index"

  
  devise_for :users
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :app
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :wrapper, :plist]
  
  # GET /versions
  # GET /versions.json
  def index
    @app = App.find(params[:app_id])
    @versions = Version.find(:all, :conditions => ["app_id = ?", params[:app_id]], :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @versions }
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
    @app = App.find(params[:app_id])
    @version = Version.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/new
  # GET /versions/new.json
  def new
    @app = App.find(params[:app_id])
    @version = Version.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/1/edit
  def edit
    @app = App.find(params[:app_id])
    @version = Version.find(params[:id])
  end

  # POST /versions
  # POST /versions.json
  def create
    @app = App.find(params[:app_id])
    
    file = params[:version][:binary_file]    
    params[:version][:filename] = file.original_filename
    params[:version].delete :binary_file
    @version = Version.new(params[:version])
    puts "** version insert"    
    respond_to do |format|
      if @version.save
  
        # file save
        tmp = file.tempfile
        dir = Rails.root.join("public", "data", @app.id.to_s(), @version.id.to_s()).to_s()
        puts "DIR = " + dir
        FileUtils.mkdir_p(dir)
        file_path = File.join(dir, file.original_filename)
        puts "file_path = " + file_path
        FileUtils.cp tmp.path, file_path        
        
        # shorten url
        Bitly.use_api_version_3
        bitly = Bitly.new('edbear', 'R_188b8934fd463d8603c25899e11944c8')
        url = wrapper_app_version_url(@app, @version, :only_path => false)
        @version.shortened_url = bitly.shorten(url).short_url
        @version.save
                
        format.html { redirect_to [@app,@version], notice: 'Version was successfully created.' }
        format.json { render json: @version, status: :created, location: @version }
      else
        format.html { render action: "new" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /versions/1
  # PUT /versions/1.json
  def update
    @app = App.find(params[:app_id])
    file = params[:version][:binary_file]    
    params[:version][:filename] = file.original_filename if file
    params[:version].delete :binary_file
    @version = Version.find(params[:id])

    respond_to do |format|
      if @version.update_attributes(params[:version])
        
        if file
          # file save
          tmp = file.tempfile
          dir = Rails.root.join("public", "data", @app.id.to_s(), @version.id.to_s()).to_s()
          file_path = File.join(dir, file.original_filename)
          puts "file_path = " + file_path
          FileUtils.rm_rf dir
          FileUtils.mkdir_p(dir)
          FileUtils.cp tmp.path, file_path
        end
        
        format.html { redirect_to app_versions_url(@app), notice: 'Version was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1/versions/1
  # DELETE /apps/1/versions/1.json
  def destroy
    @version = Version.find(params[:id])    
    if params[:app_id]
      @app = App.find(params[:app_id])
    else
      @app = @version.app
    end
    
    dir = Rails.root.join("public", "data", @app.id.to_s(), @version.id.to_s()).to_s()
    puts "DIR = " + dir
    FileUtils.rm_rf dir
    
    @version.destroy

    respond_to do |format|
      format.html { redirect_to app_versions_url(@app) }
      format.json { head :ok }
    end
  end
  
  
  
  # generate html plist
  def wrapper
    @app = App.find(params[:app_id])
    @version = Version.find(params[:id])
    
    respond_to do |format|
      format.html # wrapper.html.erb
    end    
  end
  
  def plist
    @app = App.find(params[:app_id])
    @version = Version.find(params[:id])
    
    respond_to do |format|
      format.html {render :layout => false}
    end
  end
  
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_for([@app, @version], :html => { :multipart => true } ) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app %><br />
    <%= @app.title %> (<%=@app.appid%>)
	<%= f.hidden_field :app_id, :value => @app.id%>
  </div>
  <div class="field">
    <%= f.label :revision %><br />
    <%= f.number_field :revision %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
	<%= f.label '업로드 할 파일' %><br />
	<%= f.file_field 'binary_file' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<h1><%= @app.title %></h1>

<table>
  <tr>
    <th>URL</th>
    <th>Description</th>
	<th>Last updated at</th>
<% if user_signed_in? %>
    <th></th>
    <th></th>
<% end %>
	<th></th>
  </tr>

<% @versions.each do |version| %>
  <tr>
    <td><%= link_to version.shortened_url, app_version_path(@app, version) if version.shortened_url %></td>
    <td><%= link_to version.description, app_version_path(@app, version)  %></td>
	<td><%= link_to version.updated_at.localtime, app_version_path(@app, version) %></td>
	<% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_app_version_path(@app, version) %></td>
    <td><%= link_to 'Destroy', app_version_path(@app, version), confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
	<td><a href="itms-services://?action=download-manifest&amp;url=<%=plist_app_version_path(@app, version, :only_path => false) %>" class="button"><span>INSTALL</span></a></td>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
<%= link_to 'New Version', new_app_version_path %> |
<% end %>
<%= link_to 'Back', apps_path %>

app/views/versions/new.html.erb
<h1>New version</h1>

<%= render 'form' %>

<%= link_to 'Back', app_versions_path %>

app/views/versions/plist.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>items</key>
        <array>
                <dict>
                        <key>assets</key>
                        <array>
                                <dict>
                                        <key>kind</key>
                                        <string>software-package</string>
                                        <key>url</key>
                                        <string><%=root_path(:only_path => false)+"data/%d/%d/%s" % [@app.id, @version.id, url_encode(@version.filename)] %></string>
                                </dict>
                        </array>
                        <key>metadata</key>
                        <dict>
                                <key>bundle-identifier</key>
                                <string><%=@app.appid%></string>
                                <key>kind</key>
                                <string>software</string>
                                <key>title</key>
                                <string><%=@app.title%></string>
                        </dict>
                </dict>
        </array>
</dict>
</plist>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>App:</b>
  <%= @version.app.title %>
</p>

<p>
  <b>Revision:</b>
  <%= @version.revision %>
</p>

<p>
  <b>Description:</b>
  <%= @version.description %>
</p>

<p>
  <a href="itms-services://?action=download-manifest&amp;url=<%=plist_app_version_path(@app, @version, :only_path => false) %>">Download & Install this version.</a>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_app_version_path %> |
<% end %>
<%= link_to 'Back', app_versions_path %>

app/views/versions/wrapper.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>App:</b>
  <%= @version.app.title %>
</p>

<p>
  <b>Revision:</b>
  <%= @version.revision %>
</p>

<p>
  <b>Description:</b>
  <%= @version.description %>
</p>

<p>
  <a href="itms-services://?action=download-manifest&amp;url=<%=plist_app_version_path(@app, @version, :only_path => false) %>">Download & Install this version.</a>
</p>

<%= link_to 'Edit', edit_app_version_path %> |
<%= link_to 'Back', app_versions_path %>