config/routes.rb
EasyOta::Application.routes.draw do
  resources :devices

  devise_for :users

  resources :versions
  
  resources :apps do
    resources :versions do
      get 'wrapper', :on => :member
      get 'plist', :on => :member
    end
  end

  root :to => "apps#index"

  
  devise_for :users
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appid %><br />
    <%= f.text_field :appid %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>KTH Apps</h1>

<table>
  <tr>
    <th>Title</th>
<% if user_signed_in? %>
    <th></th>
    <th></th>
<% end %>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= link_to "%s (%s)" % [app.title, app.appid] , app_versions_path(app) %></td>
	<% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path if user_signed_in? %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
	<div class="span-24">
		<h1><%= @app.title %></h1>
	</div>

<div class="span-24">
<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>
</div>